### ISSUE TITLE
Expose CPU and Memory limits as prometheus metrics

### ISSUE THREAD

**Issue by justenwalker** [jet/damon#10]
Expose the limits that are being enforced on the task as Prometheus metrics. These should just be gauges for:

- `damon_cpu_limit_hz` : CPU Rate limit converted to HZ
- `damon_cpu_limit_percent` : CPU Rate limit converted to percent of total compute on the host: Limit HZ / Total Machine HZ` (0.0 - 1.0 not 0 - 100)
- `damon_memory_limit_bytes` : Memory Limit converted to Bytes

**Comment by ddreier** [comment]
I'd like to take a stab at this. Famous last words, but I think it should be straightforward.

**Comment by justenwalker** [comment]
Sounds good @ddreier and thanks for volunteering!  If you need some help, PR what you've got and we can discuss on the PR. If you no longer want to do it, just let me know so weI can un-lick this cookie.

**Comment by justenwalker** [comment]
Closing. Implemented by #22
