### ISSUE TITLE
Unsafe DLL Loading

### ISSUE THREAD

**Issue by zx2c4** [jet/damon#18]
You're using syscall, but you should be using x/sys/windows's lazy DLL struct instead:

https://github.com/jet/damon/blob/f4a70e9a613c445a574ebf97edd53467d978f030/win32/base_types_win32.go#L11-L15

iphlpapi.dll and userenv.dll are not part of \KnownDlls.

Your [blog post](https://medium.com/jettech/breaking-all-the-rules-using-go-to-call-windows-api-2cbfd8c79724) indicates you know about the right way to do it but for some reason didn't.

**Comment by justenwalker** [comment]
Thanks for the find @zx2c4. When creating this
 Do you have time to make the PR to fix it?

**Comment by zx2c4** [comment]
I have no idea what this project does or is used for, but I thought you had an interesting Windows library so I was poking around with it. You're probably a better person to fix this than me.

**Comment by justenwalker** [comment]
Sure, just wanted to give you first dibs on fixing it if you were interested. Thank you anyway for reporting, I'll take care of it.

**Comment by zx2c4** [comment]
By the way, there's an easier way of dealing with all this using `//sys`. Check it out:

In this file (or in any file, really), I define a bunch of calls like this one:
https://github.com/WireGuard/wireguard-windows/blob/3f40da2044fd468ed05f3902608e62382b81ec9c/tunnel/firewall/syscall_windows.go#L14-L15

And then in this file, I have a go generate directive:

https://github.com/WireGuard/wireguard-windows/blob/3f40da2044fd468ed05f3902608e62382b81ec9c/tunnel/firewall/mksyscall.go#L8

Which winds up creating a file containing the fuction, like:

https://github.com/WireGuard/wireguard-windows/blob/master/tunnel/firewall/zsyscall_windows.go#L39-L52
https://github.com/WireGuard/wireguard-windows/blob/master/tunnel/firewall/zsyscall_windows.go#L90-L100

**Comment by justenwalker** [comment]
Neat, I'll take a look at this too. Thanks for the tip!
